//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.24 at 03:42:46 PM CEST 
//


package net.addictivesoftware.games.afagddu.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RenderInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RenderInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="size" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="matdef" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="color" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RenderInfo")
public class RenderInfo {

    @XmlAttribute
    protected Float size;
    @XmlAttribute
    protected String matdef;
    @XmlAttribute
    protected String color;

    /**
     * Gets the value of the size property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getSize() {
        return size;
    }

    /**
     * Sets the value of the size property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setSize(Float value) {
        this.size = value;
    }

    /**
     * Gets the value of the matdef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMatdef() {
        return matdef;
    }

    /**
     * Sets the value of the matdef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMatdef(String value) {
        this.matdef = value;
    }

    /**
     * Gets the value of the color property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColor() {
        return color;
    }

    /**
     * Sets the value of the color property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColor(String value) {
        this.color = value;
    }

}
